name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check

  branch-deploy:
    needs: [Checks]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check:format

      - name: Add env variables
        run: |
          echo "DB_FILE_NAME=${{ secrets.DB_FILE_NAME }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "WEBSITE_URL=https://lienzolima.com" >> .env
          echo "PROD=true" >> .env

      - name: Build
        run: pnpm astro build

      - name: Deploy to deploy-dist branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git fetch --all
          # Check out the deploy-dist branch or create it if it doesn't exist
          git checkout -b deploy-dist || git checkout deploy-dist
          # Reset deploy-dist to match the main branch
          git reset --hard origin/main
          # Add the dist folder and commit
          rm -rf .gitignore
          git add dist/
          git commit -m "Deploy build from main"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lienzolima-dev/platform.git deploy-dist --force
